<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Api\Module'                        => __DIR__ . '/Module.php',
    'Api\Controller\ResourceController' => __DIR__ . '/src/Api/Controller/ResourceController.php',
    'Api\Model\Exception'               => __DIR__ . '/src/Api/Model/Exception.php',
);